services:
  front:
    image: gb24-app
    build:
      context: ./tmp/grzesbank_app
      args:
        - API_PROTOCOL=https
        - API_PORT=443
        - API_HOST=localhost
        - API_PATH=/api
    container_name: gb24-app
    ports:
      - 8081:80
    networks:
      - intr
      - extr
  
  back:
    image: gb24-api
    build: ./tmp/grzesbank-api
    container_name: gb24-api
    volumes:
      - api-db:/db
    networks:
      - intr
    environment:
      - FE_BASE_URL=https://localhost
      - CRYPTO_KEY=0000000000000000000000000000000000000000000=
  
  nginx:
    image: nginx
    container_name: gb24-nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./tmp/grzesbank_app/docker_resources/ngconf.conf:/etc/nginx/conf.d/default.conf
      - ./tmp/docker_resources/private.key:/etc/ssl/private.key
      - ./tmp/docker_resources/cert.crt:/etc/ssl/cert.crt
    networks:
      - extr
      - intr

volumes:
  api-db:

networks:
  intr:
    internal: true
  extr:
    internal: false